### ISSUE TITLE
Lines for systems that require cfw2can

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/icub-os-files#3]
@xEnVrE reported that in the `.bashrc` installed in the image the lines for the system that use cfw2can are missing, while they were there on the .bashrc pre-superbuild. I checked in this repo, and it seems that actually the lines are missing in both versions:
https://github.com/icub-tech-iit/icub-os-files/tree/master/user-environment . 

@xEnVrE do you have any idea of which lines should be added? 

fyi @Uboldi80 @davidelasagna @mbrunettini @pattacini

**Comment by xEnVrE** [comment]
I was sure that the pre-superbuild had them because I remember that those lines were on the PC104 after the new image (with the new CMake) has been deployed (see https://github.com/icub-tech-iit/tickets/issues/1223) some months ago.

Nevertheless, the missing lines are

```
DRIVER_ROOT=/lib/modules/$(uname -r)/iCubDrivers/
# to be used if the corresponding hardware is mounted on the robot 
#export ESDCANAPI_DIR=${DRIVER_ROOT}/esdCanApi/
#export PLXCANAPI_DIR=${DRIVER_ROOT}/plxCanApi/
export CFW2CANAPI_DIR=${DRIVER_ROOT}/cfw002/
```

Not sure about `ESD` and `PLX`. On `iCubGenova01` we need `CFW2CANAPI_DIR` for example.

**Comment by mbrunettini** [comment]
The suggested modifications are valid for any model of iCub? Or are they bind to to some specific hardware?

**Comment by traversaro** [comment]
I just discussed with @maggia80 and he confirmed me that we can remove `ESDCANAPI_DIR` (now ESD devices on linux use the standard interface `socketcan`) and `PLXCANAPI_DIR` (cfw1, no known robot has that mounted). `CFW2CANAPI_DIR` is only relevant instead for `pc104`/live systems.

Discussing with @mbrunettini, we understood more the request of @xEnVrE : he asked to switch the `.bashrc_iCub` that is shipped with the `live`/pc104 image (that is stored in https://github.com/icub-tech-iit/icub-os-files/blob/c4c5e045ddbd9804c623ef78ec44ed0174fd6d64/scripts/icub-live/live-build/config/includes.chroot/etc/skel/.bashrc_iCub ) to match the superbuild one available in  https://github.com/icub-tech-iit/icub-os-files/blob/c4c5e045ddbd9804c623ef78ec44ed0174fd6d64/user-environment/bashrc_iCub_superbuild .

**Comment by mbrunettini** [comment]
ok, fixed in [this commit ](https://github.com/icub-tech-iit/icub-os-files/commit/bcb8ebfb1519fb229dc4b914ca84bfff5da49543)
